services:
  intermediate-server:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "/app/dist/index.js"]
