name: Notify Webhook on Package Publish

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/app


on:
  workflow_run:
    workflows: ["App Docker Image"]
    types:
      - completed

jobs:
  notify-webhook:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Send webhook notification
        env:
          WEBHOOK_URL: "https://smee.io/G84SgLL6WsdARUt"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_USERNAME: ${{ github.repository_owner }}
        run: |
          curl -X POST $WEBHOOK_URL \
          -H "Content-Type: application/json" \
          -d '{
                "action": "${{ github.event.action }}",
                "registry_package": {
                    "installation_command": "docker pull ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }})"
                },
                "username" : "${{ secrets.GHCR_USERNAME }}"
                "token": "${{ secrets.GITHUB_TOKEN }}"
              }'
