name: Notify Webhook on Package Publish

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/app


on:
  workflow_run:
    workflows: ["App Docker Image"]
    types:
      - completed

jobs:
  notify-webhook:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Send webhook notification
        env:
          WEBHOOK_URL: "https://smee.io/G84SgLL6WsdARUt"
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST $WEBHOOK_URL \
          -H "Content-Type: application/json" \
          -d @- <<EOF
          {
            "action": "${{ github.event.action }}",
            "installation_command": "docker pull ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest",
            "username": "$GITHUB_USERNAME",
            "token": "$GITHUB_TOKEN"
          }
          EOF
