name: Private Cron  Binary

on:
  push:
    branches: ["main", "119-remix-refactor"]
    paths:
      - "private-server-cron/**"
  workflow_dispatch:

jobs:
  build-and-release-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install @vercel/ncc
        run: npm i -g @vercel/ncc

      - name: Install pkg
        run: npm install -g pkg

      - name: Build server file
        run: ncc build "private-server-cron/version-checker.js

      - name: Build Linux binary
        run: pkg --targets node18-linux-x64 ./private-server-cron/dist/index.js --out-path ./private-server-cron/dist

      - name: Build Windows binary
        run: pkg --targets node18-win-x64 ./private-server-cron/dist/index.js --out-path ./private-server-cron/dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Binary release ${{ github.sha }}
          body: |
            Binaries for commit ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Linux binary to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./private-server-cron/dist/index
          asset_name: index-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows binary to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./private-server-cron/dist/index.exe
          asset_name: index-win.exe
          asset_content_type: application/octet-stream
